import config
import sys
import os 
import shutil
import glob

# nested folder generated by prep_DM_HGR.py, with the following structure
# - folder
#   - species 1
#       - species 1 file 1
#   - species 2
#       - species 2 file 1
#       - species 2 file 2
src = 'HGR_species_folder' 
dest = 'HGR_species'
label_dir = 'file2label/'

base_path = config.DM_data_path

# make dest folder
if not os.path.exists(os.path.join(base_path, dest)):
    os.mkdir(os.path.join(base_path, dest))

# concatenate all files in subdir to _combined.fna
for subdir in os.listdir(os.path.join(base_path+src)):
    with open(os.path.join(base_path, dest, subdir+"_combined.fa"), 'wb') as outfile:
        for filename in glob.glob(base_path+"/"+src+'/'+subdir+'/*.fa'):
            with open(filename, 'rb') as readfile:
                shutil.copyfileobj(readfile, outfile)


# generate label_{dir}.txt
label_id = 0
with open(os.path.join(base_path,label_dir, src+".txt"), 'w') as f:
    for fna_file in os.listdir(os.path.join(base_path, dest)):
        f.write(fna_file+"\t"+str(label_id)+"\n")
        label_id += 1

# generate name2label_{dir}.txt
label_id=0
with open(os.path.join(base_path, "name2label", src+".txt"), "w") as f:
    for fna_file in os.listdir(os.path.join(base_path, dest)):
        if fna_file.endswith('.fa'):
            cur_class = fna_file[:-3]
        elif fna_file.endswith('.fna'):
            cur_class = fna_file[:-4]
        elif fna_file.endswith('.fasta'):
            cur_class = fna_file[:-6]
        f.write(cur_class+"\t"+str(label_id)+"\n")
        label_id += 1
